# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-js:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint JS
        run: npx --yes oxlint@latest -D perf

  lint-package:
    name: Lint package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm install --no-fund --no-audit --ignore-scripts
      - run: npm run build
      - name: Run publint
        run: npx --yes publint

  check-types:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm install --no-fund --no-audit --ignore-scripts
      - name: Check types
        run: npm run check

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm install --no-fund --no-audit --ignore-scripts
      - run: npm run build
      - run: npm test
